package com.example.cqlsystechnologies.model

data class ResponseModel(
    val body: Body ? = null,
    val code: Int ? = null,
    val message: String ? = null,
    val status: Boolean ? = null
)

data class Body(
    val address: String,
    val addressId: Int,
    val addressLatitude: String,
    val addressLongitude: String,
    val adminShare: String,
    val cashback_wallet_amount: Double,
    val city: String,
    val country: String,
    val countryCode: String,
    val countryCodePhone: String,
    val createdAt: String,
    val deviceToken: String,
    val deviceType: Int,
    val dob: String,
    val email: String,
    val facebookId: String,
    val firstName: String,
    val forgotPasswordHash: String,
    val fullName: String,
    val gender: Int,
    val googleId: String,
    val id: Int,
    val ipAddress: String,
    val isAccountVerified: String,
    val isNotification: Int,
    val isOnline: String,
    val is_deleted: Int,
    val is_driver_bypass_enable: Int,
    val island_id: Int,
    val lastName: String,
    val latitude: String,
    val loginType: Int,
    val longitude: String,
    val loyality_amount: String,
    val otp: Int,
    val otpVerified: Int,
    val paymentMethod: Int,
    val phone: String,
    val phoneVerified: String,
    val photo: String,
    val postalCode: String,
    val province: String,
    val referrals_amount: Int,
    val referrals_code: String,
    val registerDate: String,
    val rememberToken: String,
    val role: Int,
    val schedule_user_status: Int,
    val socialId: String,
    val socialType: Int,
    val socketId: String,
    val status: Int,
    val token: String,
    val totalCredit: String,
    val uniqueId: String,
    val unique_time: String,
    val updatedAt: String,
    val used_loyality_amount: String,
    val user_referrals_order_count: Int,
    val user_timezone: String,
    val username: String,
    val walletAmount: String,
    val walletPin: String,
    val wrongAttemptBlock: String,
    val wrongAttemptCount: String
)